Int 2019 83 General design improvements for admin dashboard functions
marianlaslo/VikingVault pull request #78
Opened 2019-08-28 12:39 UTC by vladbuda

2019-08-28 12:48 UTC, Slitthe commented on ClientApp/viking-vault/src/AdminDashboard/AddMoneyModal.tsx
> +        if(Number(this.state.amount) < this.state.minAmount || Number(this.state.amount) > this.state.maxAmount || !(this.state.amount.match("^[-+]?[0-9]*\.?[0-9]+([-+]?[0-9]+)?$"))){
At this point it would be better to just separate each of the items in the `||` chain into their own variables and use them

2019-08-28 14:04 UTC, vasi-axinte requested changes

2019-08-28 14:04 UTC, vasi-axinte commented on ClientApp/viking-vault/src/AdminDashboard/AddMoneyModal.tsx
> +        return{
You need a space after return.

2019-08-29 07:12 UTC, Slitthe commented on ClientApp/viking-vault/src/AdminDashboard/AddMoneyModal.tsx
> +        let isAmountSmallerThanLimit = Number(this.state.amount) < this.state.minAmount;
🚨👮‍♂️JS Good Practice police says that you should use `const` if you don't reassign the variables

2019-08-29 07:29 UTC, merged